// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOogaaCRdhabEDxcx4AIJXTLOb_DtwFKU',
    appId: '1:1028173841251:web:011d99ab8c3258c1768956',
    messagingSenderId: '1028173841251',
    projectId: 'events-app-a9c3c',
    authDomain: 'events-app-a9c3c.firebaseapp.com',
    storageBucket: 'events-app-a9c3c.firebasestorage.app',
    measurementId: 'G-BXE5M39CVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsoA8nQjo02K9PLmz2R4C3wysjoktyIxM',
    appId: '1:1028173841251:android:ec1ae4d65876278c768956',
    messagingSenderId: '1028173841251',
    projectId: 'events-app-a9c3c',
    storageBucket: 'events-app-a9c3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ20PfGUMmI_fXmfobP0SHgy9P_zM7O2A',
    appId: '1:1028173841251:ios:9ab010317131405d768956',
    messagingSenderId: '1028173841251',
    projectId: 'events-app-a9c3c',
    storageBucket: 'events-app-a9c3c.firebasestorage.app',
    androidClientId: '1028173841251-44rec4jaa1v40gh2o9pdvgvirdqsvofs.apps.googleusercontent.com',
    iosClientId: '1028173841251-tueqhsnbjl4i14rncdtm3lp0s189rcki.apps.googleusercontent.com',
    iosBundleId: 'com.bander.camzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ20PfGUMmI_fXmfobP0SHgy9P_zM7O2A',
    appId: '1:1028173841251:ios:9ab010317131405d768956',
    messagingSenderId: '1028173841251',
    projectId: 'events-app-a9c3c',
    storageBucket: 'events-app-a9c3c.firebasestorage.app',
    androidClientId: '1028173841251-44rec4jaa1v40gh2o9pdvgvirdqsvofs.apps.googleusercontent.com',
    iosClientId: '1028173841251-tueqhsnbjl4i14rncdtm3lp0s189rcki.apps.googleusercontent.com',
    iosBundleId: 'com.bander.camzone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOogaaCRdhabEDxcx4AIJXTLOb_DtwFKU',
    appId: '1:1028173841251:web:ecb80abc05489544768956',
    messagingSenderId: '1028173841251',
    projectId: 'events-app-a9c3c',
    authDomain: 'events-app-a9c3c.firebaseapp.com',
    storageBucket: 'events-app-a9c3c.firebasestorage.app',
    measurementId: 'G-D40M7SD952',
  );
}
